feat: add lockZoom & lockPan
zakodium-oss/react-roi pull request #86
Opened 2023-12-12 14:13 UTC by Sebastien-Ahkrin

close: https://github.com/zakodium-oss/react-roi/issues/84

2023-12-13 10:56 UTC, stropitek requested changes
There is a another place (over an ROI) where the cursor must be handled with the `lockPan` option in mind.

Why call the option "lock" and then the stories "disabled"? I'm not against "disable" but you should pick one and be consistent with the terminology.

2023-12-13 10:56 UTC, stropitek commented on src/components/container/ContainerComponent.tsx
> +  if (lockPan) return 'default';
It's more complicated than that...

For example now when the mode is 'draw', the default cursor can appear which is wrong

2023-12-13 14:14 UTC, Sebastien-Ahkrin commented
> There is a another place (over an ROI) where the cursor must be handled with the `lockPan` option in mind.

I'm not really sure about what you said ... If I hover a ROI with lockPan, I have this result (I tested that) this doesn't have to look like that ?

https://github.com/zakodium-oss/react-roi/assets/30870051/06472cc1-b1c1-4dd2-ab34-799268d33592

2023-12-15 10:06 UTC, stropitek approved these changes

2023-12-15 10:06 UTC, merged